config/routes.rb
Rails.application.routes.draw do
  resources :register_admins
  resources :registers
  resources :subjects
  resources :categories
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  root  "static_pages#home"
  match "/signin", to: "sessions#new", via: "get"
  match "/signout", to: "sessions#destroy", via: "delete"
  match "/signup", to: "users#new", via: "get"
  match "/help", to: "static_pages#help", via: "get"
  match "/about", to: "static_pages#about", via: "get"
  match "/contact", to: "static_pages#contact", via: "get"
  match "/update/:register_id", to: "registers#update", as: "registers_update", via: :patch
end

app/controllers/register_admins_controller.rb
class RegisterAdminsController < ApplicationController
  def index
    @registers = Register.all.order "created_at DESC"
  end

  def edit
    @register = Register.find params[:id]
    @answer_sheets = @register.answer_sheets
  end

  def update
    @register = Register.find params[:register][:id]
    if @register.update_attributes register_params
      flash[:success] = "checked success"
    end
    redirect_to register_admins_url
  end

  def destroy
    Register.find(params[:id]).destroy
    flash[:success] = "User deleted."
    redirect_to register_admins_url
  end

  private

    def register_params
      params.require(:register).permit(:category_id, 
                                 answer_sheets_attributes: [:answer_id, :correct]) 
    end
end

app/views/register_admins/edit.html.erb
<% provide(:title, "Test") %> 
<h1> 
  <%= @register.subject.context_display %> 
</h1> 
<%= form_for @register do |f| %> 
  <%= f.hidden_field :id %>
<div class="register_edit"> 
<% @answer_sheets.each do |answer_sheet| %> 
      <span><%= answer_sheet.question.context_question %></span> 
      <ul> 
        <%= f.fields_for :answer_sheets,  answer_sheet do |ff| %>
          <% answer_sheet.answers.each do |answer|%>
            <li>
              <% if answer.id == answer_sheet.answer_id %>
                <%= ff.radio_button :answer_id, answer.id, checked: true %> 
                <%= answer.answer %>
                <span>checked</span>
              <% else %>
                <%= ff.radio_button :answer_id, answer.id, checked:false %> 
                <%= answer.answer %>
              <% end  %>
            </li>
          <% end %> 
            <li>
              <%= ff.check_box :correct %>
            </li> 
        <% end %> 
      </ul> 
    <% end %> 
  <%= f.submit "Save changes", class: "btn btn-large btn-primary" %> 
</div> 
<% end %>

app/views/register_admins/index.html.erb
<% provide(:title, 'All register') %>
<h1>All register</h1>
<div class="registed">
  <ul>
    <% @registers.each do |register| %>
      <li>
        <% if !register.start? %>
            <span><%= register.subject.context_display if  register.subject %></span>
            <span>Test</span>
            <span>00:00:00</span>
            <span><%= link_to "Start", edit_register_path(register) %></span>
        <% elsif !register.finish? %>
            <span>
              <h3><%= DateTime.parse(register.date_test.to_s).strftime("%d/%m/%Y %H:%M:%S") %></h3>
            </span>
            <span>Testing</span>
            <span> </span>
            <span> </span>
        <% else %>
            <span>
              <%= register.subject.context_display if register.subject%>
            </span>
            <span>Checked</span>
            <span><h4><%= register.count_correct %>/<%= register.subject.count_question if register.subject%></h4></span>
            <span><%= link_to "View", register_path(register) %></span>
        <% end%>
        <span>
          <%= link_to "check", edit_register_admin_path(register) %>
        </span>
        <span>
          <%= link_to "delete", register, method: :delete,
                                  data: { confirm: "You sure?" } %>
        </span>
      </li>
    <% end %>
  </ul>
</div>